In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [7]:
my_array = np.array(my_list)

In [8]:
my_array

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.random.rand(4,4)

array([[0.07885926, 0.52199267, 0.00775223, 0.06488882],
       [0.62621507, 0.95026799, 0.95156022, 0.91084312],
       [0.84723825, 0.39495774, 0.57695239, 0.09699189],
       [0.91557047, 0.37627191, 0.73775041, 0.20482101]])

In [33]:
np.random.randn(3,3)

array([[-0.55368393,  0.03199714,  0.33694009],
       [ 0.82834273,  2.47211942, -0.92243425],
       [-0.39191942,  0.54667838,  0.13620026]])

In [35]:
np.random.randint(1,200,10)

array([ 88, 139, 155,  11,  81,  93, 170, 105, 195,  30])

In [40]:
arr = np.arange(0,25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr.shape

(5, 5)

In [47]:
arr.dtype

dtype('int32')